### ISSUE TITLE
The e function shouldn't call emacsclient if it's not installed

### ISSUE THREAD

**Issue by r-darwish** [drrlvn/fish#19]

**Comment by drrlvn** [comment]
It's not set as the default editor or anything like that, it's just meant to be a convenient wrapper. What do you think it should do if `emacsclient` isn't available?

**Comment by drrlvn** [comment]
@r-darwish Any suggestions for what `e` should do if `emacsclient` isn't installed?

**Comment by r-darwish** [comment]
I think we can just close this. I agree with what you're saying - `e` stands for "Emacs" and not for "Edit". It's a shortcut specific for Emacs.
